BASE_TASK_CONFIG_PATH: "configs/exploration/gibson_evaluate_noisy.yaml"
TRAINER_NAME: "occant_exp"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 0
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "eval_tb"
VIDEO_DIR: "video_dir"
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/OccAnt(rgb)/ckpt.11.pth"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_EPISODES: 10000
T_EXP: 500
# ---------------zty-------------------
EXPERIMENT_NAME: "EXPS/baseline/occant_rgb(N)_eval"
USE_TIMESTAMP: True
#CONTINUE: True
# ---------------zty-------------------
EVAL:
  USE_CKPT_CONFIG: False

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    num_mini_batch: 1
  ANS:
    reward_type: 'area_seen'
    image_scale_hw: [128, 128]
    MAPPER:
      map_size: 65
      num_mapper_steps: 100
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
#      num_update_batches: 50
      map_batch_size: 21
      use_data_parallel: True
      replay_size: 50
      gpu_ids: [0]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgb'
      GP_ANTICIPATION:
        wall_fov: 120.0
        resnet_type: 'resnet18'
        unet_nsf: 16
#        detach_depth_proj: False
#        pretrained_depth_proj_model: "trained_models/ans_rgb/run_00/checkpoints/ckpt.12.pth"
#        freeze_depth_proj_model: False
    LOCAL_POLICY:
      learning_algorithm: 'rl'